### ISSUE TITLE
Vertaisarviointi 29.9.

### ISSUE THREAD

**Issue by jmakine** [tomjtoth/tsoha-harjoitustyo#2]
**Tuotannossa testaaminen:**

Rekisteröityminen, ulos ja sisäänkirjautuminen toimi. Ulkoasu on miellyttävä, visualisoinnit herättää datan mukavasti henkiin. Navigointi sivujen välillä on selkeää ja kaikki otsikot kuvaavia.

Jossain voisi näkyä oma veriryhmä, ihan vaikka tekstinä ”Tervetuloa, ...” -tekstin perässä. Ihan oikea verenluovuttaja kyllä muistaa oman veriryhmänsä, että sinänsä ei varmaan tosielämän ongelma. Huomasin, että pääsivun kuvaajat eivät suodata toisiaan valintoja klikkaillessa. Se olisi hieno ominaisuus, mutta tähän 5op sovellukseen käytettävissä oleva aika on hyvin rajallinen.

Ensimmäiset lisäämäni luovutukset per luovutuspaikka tuli näkyviin kaikkiin taulukoihin. Kun lisäsin toisen luovutuksen samalle päivälle, mutta eri luovutuspaikkaan, tuli se näkyviin sekä ’Luovutuspaikkojen perusteella’ että ’Omat luovutukset’ -taulukkoon, mutta ei ’Veriryhmien perusteella’ -taulukkoon. Kun lisäsin uuden luovutuksen samalle paikalle ja päivälle, ei niitä näkynyt enää missään taulukossa. Kaikki kertomukseni näkyi Kertomukset -sivulla.

Reaalielämässähän tällaisia useita luovutuksia samalle päivälle ei tapahdu, mutta kenties saman päivän luovutukset samalta henkilöltä voisi estää kokonaan pääsemästä tietokantaan, jolloin se ei tulisi näkyviin mihinkään taulukkoon eikä kertomuksiin. Tästä aikarajoitteesta onkin maininta README.md:n jatkokehityksissä, eli asian ydin selvästikin huomioitu.

Mutta kun rekisteröin muutaman muunkin luovuttajan, niin huomasin että samalla veriryhmällä tai samaan luovutuspaikkaan tehdyt luovutukset eivät summaannu kuvaajissa. Kaksi eri luovuttajaa samalla veriryhmällä samalle päivälle ja paikalle näyttää yhä vain yhtä kappaletta veriryhmissä ja luovutuspaikoissa.

**Koodi ja tietokannan rakenne:**

Tietokanta on rakennettu hyvin, lyhyesti ja ytimekkäästi. Reitit määritelty selkeästi, samoin kun siellä käytetyt funktiot muista fileista. Koodia on mukava lukea, kun nimet on selkeitä, kuvaavia ja lyhyitä. Koodin rakenne kaiken kaikkiaan hyvin jaettu selkeisiin kokonaisuuksiin, ja koodi sisennetty ja kirjoitettu ohjeistuksen mukaisesti. schema.sql tosin sisältää sekä pienellä että isolla kirjoitettuja select ym. sanoja.

Kurssin teknisen tarkistuslistan ohjeen mukaan ”SELECT *” -lauseketta ei tulisi käyttää, mutta ainakin consumables.py, users.py ja clinics.py sisältää tällaiset.

README näyttää olevan ajan tasalla, ja se kuvaa hyvin, mistä on kyse.

**Comment by tomjtoth** [comment]
with 67a28060bcbbdb1646413961b6a3bd32f27e9de0 the user can see their blood type, also the `select *` from `users.py` is now removed

**Comment by tomjtoth** [comment]
with 1ef0a8a09e5badcb81ff631a62ffb22bcf005919 `select *` removed from `clinics.py` and `consumables.py`

**Comment by tomjtoth** [comment]
leaving this open for the future implementation of more realistic limits on donation.

**Comment by tomjtoth** [comment]
#1 is open also for fixing the DB queries
