### ISSUE TITLE
Vertaisarviointi 13.10.23

### ISSUE THREAD

**Issue by yogajones** [tomjtoth/tsoha-harjoitustyo#5]
Tosi kiva idea!

Testasin paikallisesti. Ohjeet testaukseen olivat selkeät ja toimivat.

Ihan alkuun olisin käyttäjänä kaivannut sovelluksen esittelyä: kenelle se on suunnattu, mitä ominaisuuksia siinä on ja miten niitä käytetään. Esittelyn yhteyteen voisi laittaa disclamerin siitä, ettei sivusto ole kytköksissä SPR:iin, jolloin footer vapauttaisi vähänkään pienemmiltä ruuduilta tilaa sivun varsinaiselle sisällölle.

Yritin kirjautua sisään siten, että keksin päästäni tunnukset: "huuhuu" ja salasanan "haahaa" - en siis vielä rekisteröitynyt käyttäjäksi. Kuten odotinkin, sivu näytti virheilmoituksen virheellisestä käyttäjätunnuksesta tai salasanasta, hyvä! Tämän jälkeen olisi kätevää, jos käyttäjälle tarjottaisiin 'Takaisin'-nappi, jottei tarvitsisi käyttää selaimen 'Edellinen sivu'-nappia päästääkseen yrittämään kirjautumista uudelleen.

Yritin luoda käyttäjän. Rekisteröinti ei kuitenkaan onnistunut, sillä sekä "Hoo Moilanen", "Huuhaa Moilanen" että pelkkä "Moilanen" eivät kelvanneet nimikenttään. Tästä johtuen en päässyt testaamaan muita toimintoja.

Sivun rakenne on hyvä ja selkeä ja sivustolla on helppo navigoida kannettavalla tietokoneella. Ulkoasu on kurssin tavotteisiin nähden oikein hyvä. Dark mode kiva bonus, fun mode puolestaan hassu. :D

Lähdekoodissa hyödynnetty moduuleita ja funktioita hyvin. Tämänkaltaiset rivit ovat itselleni turhan tiiviitä:

`    if int(db.session.execute(text("select count(*) from clinics")).fetchone()[0]) == 0:`

, joskin haitta lähinnä kosmeettinen ja kaiketi makuasia. Commitit näyttää olevan hyvin kuvailtu ja paketoitu.

Tässä vaiheessa keskittyisin nyt hiomaan käyttäjäkokemusta: ohjeistamaan sivuston käyttäjää, selittämällä sovelluksen toimintaa ja esimerkiksi kertomalla, miksi pääsivulla esitetty data on käyttäjälle kiinnostavaa.

Hyvää työtä, tsemppiä loppurutistukseen!

**Comment by tomjtoth** [comment]
nojoo, nimikenttä vaatii pilkun eristämään `sukunimet` + `,` +  `etunimet`, kuten placeholder:sta näkyy :D tohon toinenkin on jäänyt jo jumiin...

**Comment by tomjtoth** [comment]
tässä e730286c9a678526ddabf7f26c09fff2ecf3167c lisätty kuvaavampi title attribuutti, jotta tulevat testaajat eivät jäisi jumiin `,` puutteeseen

**Comment by tomjtoth** [comment]
tässä 1bb04a1854117aa7e1f7583cf5f1e673919ba7c5 takaisin linkki lisätty error.html:ään

**Comment by tomjtoth** [comment]
tässä 283cdc572b55911e2839eacba751614fd0f359c0 footer supistettu, *ehkä* siirrän sinne noita dark/fun emojeita

**Comment by tomjtoth** [comment]
tiiveitä koodiriveja en koske :)

**Comment by tomjtoth** [comment]
6602813465af322b599f6c74b5c0148396402317 lisää enempää ohjeistusta käyttäjille

**Comment by tomjtoth** [comment]
suurin osa yllä pyynnöistä toteutettu, kiitos arviosta!
